CREATE SEQUENCE SEQ_EMPLOYEE ;
CREATE TABLE TB_EMPLOYEE (ID_EMPLOYEE INTEGER DEFAULT NEXTVAL('SEQ_EMPLOYEE') PRIMARY KEY,PASSWORD VARCHAR(20), BIOMETRIC_PASSWORD VARCHAR(30),
ADDRESS VARCHAR(30), PHONE_RES VARCHAR(12),PHONE_CEL VARCHAR(12), NM_EMPLOYE VARCHAR(50),NICKNAME VARCHAR(30), REGISTRATION VARCHAR(20));
CREATE SEQUENCE SEQ_ROLE ;
CREATE TABLE TB_ROLE (ID_ROLE INTEGER DEFAULT NEXTVAL('SEQ_ROLE') PRIMARY KEY,NAME_ROLE VARCHAR(30), LEVEL_ROLE INTEGER);
CREATE SEQUENCE SEQ_ALLOWANCES ;
CREATE TABLE TB_ALLOWANCES (ID_ALLOWANCES INTEGER DEFAULT NEXTVAL('SEQ_ALLOWANCES') PRIMARY KEY,TIME_ALLOWANCE TIMESTAMP, TIME_TOLERED TIMESTAMP,DATE_ALLOWANCE DATE,DS_JUSTIFICATION VARCHAR(50));
CREATE SEQUENCE SEQ_DRIVE ;
CREATE TABLE TB_DRIVE (ID_DRIVE INTEGER DEFAULT NEXTVAL('SEQ_DRIVE') PRIMARY KEY,TIME_DRIVE TIMESTAMP, FL_ADJUST TIMESTAMP,DATE_DRIVE DATE, DS_JUSTIFICATION VARCHAR(50));
ALTER TABLE TB_DRIVE ADD COLUMN PID_EMPLOYEE INTEGER NOT NULL ;
ALTER TABLE TB_DRIVE ADD CONSTRAINT ID_EMPLOYEE_FK FOREIGN KEY (PID_EMPLOYEE) REFERENCES TB_EMPLOYEE(ID_EMPLOYEE)ON UPDATE CASCADE;
ALTER TABLE TB_EMPLOYEE ADD COLUMN PID_ROLE INTEGER NOT NULL ;
ALTER TABLE TB_EMPLOYEE ADD CONSTRAINT ID_ROLE_FK FOREIGN KEY (PID_ROLE) REFERENCES TB_ROLE(ID_ROLE);